### ISSUE TITLE
Ошибка после установки pod-file

### ISSUE THREAD

**Issue by ProjectoBanano** [TinkoffCreditSystems/tinkoff-asdk-ios#1]
Downloads/tinkoff-asdk-ios-master 2/SampleProject/Pods/Target Support Files/Pods-ASDKSampleApp/Pods-ASDKSampleApp-frameworks.sh: No such file or directory 

Подскажите решение

**Comment by ProjectoBanano** [comment]
Решение найдено удалением кастомного скрипта из Build Phases - для чего вообще использовался этот скрипт?

**Comment by artyomkiss** [comment]
@ProjectoBanano Насколько я понимаю, ты пытаешься собрать тестовый проект после установки подов. Описанная тобою проблема у меня не воспроизводится.
Возможно, был закэширован старый комит под тегом 1.0.0, т.к. в первые дни я двигал тэг 1.0.0 по коммитам.
 
Попробуй удалить Pods, выполнить 
`pod cache clean --all`
и уже после еще разок
`pod install`.
