### ISSUE TITLE
Перевод на Swift

### ISSUE THREAD

**Issue by kiokumicu** [TinkoffCreditSystems/tinkoff-asdk-ios#10]
Планируется перевод проекта на Swift ?

**Comment by kiokumicu** [comment]
Я так понимаю это значит нет ?)

**Comment by goharika** [comment]
I want to ask the same.
Also I am trying now translate by myself, just getting issue in TransactionHistoryModelController, on init part. There is dataSource property which type is NSArray, in the swift I have make it [Any], as you know we can't call append() function for this type, but can't find which type should be this dataSource property?

**Comment by slavabuv** [comment]
this is 'NSDictionary'

**Comment by goharika** [comment]
I have tried my self to turn it to swift, just the example which is exist with objective C.
Happy to share with you [Tiknoff Swift](https://github.com/goharika/Tinkoff-Swift)
May help someone
Need to add transactions part too, for checking

**Comment by romansavrulin** [comment]
@goharika Nice effort! Do you plan to support Carthage?

**Comment by slavabuv** [comment]
swift version https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS
