### ISSUE TITLE
Unsupported URL

### ISSUE THREAD

**Issue by svatrous** [TinkoffCreditSystems/tinkoff-asdk-ios#13]
При попытке оплаты не устанавливается правильный URL запросов.

- (void)apiVersion:(APIVersion)apiVersion path:(NSString *)path parameters:(NSDictionary *)parameters success:(void (^)(NSDictionary *responseDictionary, NSURLResponse *response))success  failure:(void (^)(ASDKAcquringApiError *error))failure
            {
                NSURLSessionConfiguration *configuration = [NSURLSessionConfiguration defaultSessionConfiguration];
                NSURLSession *session = [NSURLSession sessionWithConfiguration:configuration];
                
                NSString *domainPath = self.domainPath;
                if (apiVersion == APIVersion_v2)
                {
                    domainPath = self.domainPath_v2;
                }

После выполнения условия if domainPath = nil и оплата не проходит с ошибкой -1002 "URL не поддерживается"

**Comment by slavabuv** [comment]
fixed
