### ISSUE TITLE
Не удается совершить оплату. 

### ISSUE THREAD

**Issue by LastSprint** [TinkoffCreditSystems/tinkoff-asdk-ios#14]
Здравствуйте. Не проходит оплата в том случае, если в SDK передается число с ненулевой дробной частью. То есть, если amount = 4692000, то оплата проходит успешно, однако, если amount = 720800.95 то возвращается `Error Domain=ru.tcsbank.asdk Code=9999 "(null)" UserInfo={errorDetails=Неверный токен. Проверьте пару TerminalKey/SecretKey., errorMessage=Неверные параметры., acquringResponse=ASDKAcquiringResponse`, хотя в примере передается double.
В связи с этим есть 2 вопроса:
1) Почему из-за неправильной суммы возвращается ошибка `Проверьте пару TerminalKey/SecretKey`
2) Как все таки работать с SDK?

**Comment by slavabuv** [comment]
Добрый день!
Посмотрите тестовый пример, в нем есть товары для оплаты на сумму 100000,45 руб и 200,00 руб  в методе оплаты PayController buyItemWithName .... передаются эти суммы в NSNumber. При оплате SDK само приведет сумму в нужному виду для запроса. Если вы используете публичные методы ASDKPaymentFormStarter то сумму надо передавать как и в тестовом примере "100000,45" "200"
[NSNumber numberWithDouble:100000,45]
[NSNumber numberWithDouble:200]

**Comment by LastSprint** [comment]
Да, мы используем `ASDKPaymentFormStarter.presentPaymentForm(....)` в качестве `amount` туда передается число, округленное до сотых, предварительно приведенное к `NSNumber` (`NSNumber(value: amount)` где amount имеет тип `Double`) . А именно на сумму 720800.95 возвращается ошибка оплаты, при этом на 720800 все проходит отлично (`amount = Int(720800.95`)).

**Comment by slavabuv** [comment]
>И что будет, если в SDK в качестве amount передавать число с 3мя и более числами после запятой?
для  API это будет ошибочным форматом. Нужно передавать с целыми копейками.
