### ISSUE TITLE
Как протестировать ApplePay c тестовым терминалом?

### ISSUE THREAD

**Issue by domr** [TinkoffCreditSystems/tinkoff-asdk-ios#16]
Карты с https://oplata.tinkoff.ru/landing/develop/test нельзя добавить в ApplePay

**Comment by slavabuv** [comment]
https://oplata.tinkoff.ru/landing/develop/test это не настоящие карты поэтому их нельхя добавить в ApplePay

**Comment by slavabuv** [comment]
используйте тестовый терминал:
[ASDKAcquiringSdk setDebug:YES];
[ASDKAcquiringSdk setTestDomain:YES];
