### ISSUE TITLE
Креш при сканировании карты

### ISSUE THREAD

**Issue by Nikolaev** [TinkoffCreditSystems/tinkoff-asdk-ios#17]
ASDKPaymentFormViewController.m строчка 906

NSLog(@"scanned number %@, ecpired date %@", [cardRequisites number], [cardRequisites expireDate]);

**Comment by cashman2100** [comment]
Стабильно крэшит на iPhone 6S iOS11

**Comment by slavabuv** [comment]
по каким причинам крешит?

**Comment by slavabuv** [comment]
@Nikolaev 
>ASDKPaymentFormViewController.m строчка 906
>NSLog(@"scanned number %@, ecpired date %@", [cardRequisites number], [cardRequisites expireDate]);

@cashman2100 
>Стабильно крэшит на iPhone 6S iOS11

по каким причинам крашит, прикрепите логи

**Comment by Nikolaev** [comment]
@slavabuv 
![2018-03-10 21 28 48](https://user-images.githubusercontent.com/628002/37244388-172ef28c-24aa-11e8-83f9-db45ad2058a8.png)

**Comment by slavabuv** [comment]
пробуйте 1.3.10 (обновите pod)

**Comment by Nikolaev** [comment]
Проблема осталась.
[__NSCFString cardNumber]: unrecognized selector sent to instance
Вот сюда, в качестве cardRequisites приходит строка с распознанным номером карты, вместо объекта типа id<ASDKAcquiringSdkCardRequisites>.  
[cardScanner scanCardSuccess:^(id<ASDKAcquiringSdkCardRequisites> cardRequisites) {

**Comment by slavabuv** [comment]
в SDK нет таких вызовов
>[cardScanner scanCardSuccess:^(id cardRequisites) 
в качестве сканер может выступать любой объект который реализует протокол ASDKAcquiringSdkCardScanner для которого в качестве параметров блока success принимает любой объект реализующий протокол ASDKAcquiringSdkCardRequisites 
поэтому в [cardScanner scanCardSuccess:^(id cardRequisites) надо передавать не строку а обхект который реализует протокол ASDKAcquiringSdkCardRequisites
в тестовом примере это можно посмотреть в ASDKCardIOScanner

**Comment by Nikolaev** [comment]
@slavabuv 
В своем приложении мы используем класс ASDKPaymentFormViewController, который является частью пода ASDKUI.
В нем есть метод scanCard. 
https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/2b0b5987287e97a39dcd34629d9b2546a2235c7a/ASDKUI/Payment/PaymentViewController/ASDKPaymentFormViewController.m#L891
В этом методе и происходит креш.
Это класс из вашего SDK.  

Если, поможет, то креш происходит при распознавании номера счета карты, дата не распознается.

**Comment by slavabuv** [comment]
@Nikolaev
>
>пробуйте 1.3.10 (обновите pod)
>

вы используете версию от 27 ноября 2017 года
нужно использовать версию 1.3.10 
https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/master/ASDKUI/Payment/PaymentViewController/ASDKPaymentFormViewController.m

https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/f8937417b47955fa8c0ef736053f72d8d7211488/ASDKUI/Payment/PaymentViewController/ASDKPaymentFormViewController.m#L904

**Comment by slavabuv** [comment]
1:
>pod 'CardIO'
>pod 'ASDKCore', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKCore.podspec"
>pod 'ASDKUI', :podspec =>  "https://raw.githubusercontent.com/TinkoffCreditSystems/tinkoff-asdk-ios/master/ASDKUI.podspec"

или  2:
>pod 'CardIO'
>pod 'ASDKCore', '~> 1.3.10'
>pod 'ASDKUI', '~> 1.3.10'

**Comment by Nikolaev** [comment]
@slavabuv Используется последняя версия SDK из master.

**Comment by slavabuv** [comment]
Протокол сканирования, новая реализация есть в тестовом примере ASDKAcquiringSdkCardScanner v1.3.9 и выше
Если вы реализацию из тестового примера то обновите/возьмите новую реализацию из тестового примера  https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/master/SampleProject/ASDKSampleApp/Source/ASDKCardIOScanner.m
