### ISSUE TITLE
Не работают платежи в sample app

### ISSUE THREAD

**Issue by suzhaev** [TinkoffCreditSystems/tinkoff-asdk-ios#19]
Скачиваю SDK, запускаю пример, ввожу данные своего тестового терминала. Беру тестовую карту для успешного платежа. Ошибка:
![simulator screen shot - iphone 8 plus - 2018-04-23 at 14 54 17](https://user-images.githubusercontent.com/19522238/39125008-394c875c-4706-11e8-9059-6c8ba5fbcbee.png)

данные перепроверял несколько раз, меняю переменные kASDKTestTerminalKey1, kASDKTestPassword, kASDKTestPublicKey

**Comment by suzhaev** [comment]
При этом если запустить пример как есть, ничего не меняя, оплата проходит успешно.

**Comment by slavabuv** [comment]
Судя из названия ошибки и по шагам тестирования не работает терминал, а не "платежи в sample app" нужно обратиться в тех поддержку чтобы терминал заработал (его настроили для оплаты)
1 тестовые карты для оплаты https://oplata.tinkoff.ru/landing/develop/test
2 для разрешения вопросов по тестовому терминалу обратитесь в oplata@tinkoff.ru card_acquiring@tinkoff.ru либо к вашему персональному менеджеру.

**Comment by suzhaev** [comment]
@slavabuv мы с веба с этих терминалов уже как пару месяцев принимаем платежи и там все работает. Кажется, ошибка не в этом?

**Comment by slavabuv** [comment]
Для решения этой ситуации нужно обратиться:
1 oplata@tinkoff.ru card_acquiring@tinkoff.ru либо к вашему персональному менеджеру.
Либо:
2 выложить сюда ключи пароли от терминала и будем решать тут.

**Comment by suzhaev** [comment]
Написал, спасибо!
