### ISSUE TITLE
Crash tinkof-ASDK-ios when enter card number

### ISSUE THREAD

**Issue by evgzor** [TinkoffCreditSystems/tinkoff-asdk-ios#20]
Using ASDKCore (1.3.12)
Using ASDKUI (1.3.12)
Step to reproduce:
1. Call payment screen input card number: 4300 0000 0000 0777
when last digit done get crash in sdk: 
<img width="733" alt="screen shot 2018-05-07 at 21 48 55" src="https://user-images.githubusercontent.com/5227456/39982250-63915284-575c-11e8-942f-3df7634ad9c6.png">

crash logs:
[sh_project  13-05-2018, 19-03.crash.zip](https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/files/1999604/sh_project.13-05-2018.19-03.crash.zip)

**Comment by evgzor** [comment]
Bug not fixed.

**Comment by evgzor** [comment]
Bug not fixed in 1.3.14

**Comment by evgzor** [comment]
index

**Comment by slavabuv** [comment]
Решение:
https://developer.apple.com/documentation/code_diagnostics/address_sanitizer/enabling_the_address_sanitizer

**Comment by evgzor** [comment]
Its does not help.

**Comment by slavabuv** [comment]
@evgzor   https://developer.apple.com/documentation/code_diagnostics/address_sanitizer/enabling_the_address_sanitizer - нужно выключить "Address Sanitizer"

**Comment by evgzor** [comment]
@slavabuv did u understand the English 
![2018-11-07 12 19 18](https://user-images.githubusercontent.com/5227456/48121980-7408db80-e287-11e8-9195-fc8c8d27cbad.png)
I will escalate the issue !

**Comment by slavabuv** [comment]
I suggest to call (phone or telegram or skype) and resolve this issue

**Comment by evgzor** [comment]
skype: zorinswis
