### ISSUE TITLE
ErrorCode = 308

### ISSUE THREAD

**Issue by GevorgNanyan** [TinkoffCreditSystems/tinkoff-asdk-ios#21]
когда я пытаюсь изменить параметры на исходные (ключ терминала, пароль ....), там просто появляется ошибка 308

 failure Error Domain=ru.tcsbank.asdk Code=308 "(null)" UserInfo={errorMessage=The amount in the check and in the payment do not match., acquringResponse=ASDKAcquiringResponse object with data:
{
    ErrorCode = 308;
    Message = "The amount in the check and in the payment do not match.";
    Success = 0;
}}

**Comment by slavabuv** [comment]
`ErrorCode = 308;
Message = "The amount in the check and in the payment do not match.";`
Сумма оплаты и сумма в чеке должны совпадать [Init - создание заказа, Структура объекта Receipt](https://oplata.tinkoff.ru/landing/develop/documentation/Init)
В [SampleProject](https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/tree/master/SampleProject) из списка товаров оплатить можно товар на сумму 200р. другие суммы будут отбиваться с такой же ошибкой.

**Comment by artemKolyadin** [comment]
На данный момент судя по всему работает в обратном порядке. Если в чеке и параметре метода значения amount НЕ совпадают - все срабатывает. Если же в receiptData указать
`let receiptData: [String: Any] = [
      "Email": "user@mail.com",
      "Taxation": "osn",
      "Items": [
        ["Name": "Название товара 1", "Price": 100, "Quantity": 1, "Amount": 100, "Tax": "vat10", "Ean13": "0123456789",
         "ShopCode": "12345"],
      ]]`

И в метод  .presentPaymentForm передать amount: 100, возвращается с ошибкой 308. 

Подскажите пожалуйста, в чем может быть проблема?

**Comment by romansavrulin** [comment]
Столкнулся с этим же. Техподдержка делает круглые глаза. Мол, покажите где неправильно, формируйте правильный объект. Но, господа, вы же даете тестовое демо приложение, правда? Разве не ваша задача сделать так, чтобы оно правильно считало суммы?

**Comment by romansavrulin** [comment]
UPD: Сейчас в приложении платежи захардкожены и никак не связаны с базой данных товаров

https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/63cffc7e542ccd1c2c3810a9f84afe4f1e121412/SampleProject/ASDKSampleApp/Source/DetailInfo/DetailInfoTableViewController.m#L246-L250

https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/63cffc7e542ccd1c2c3810a9f84afe4f1e121412/SampleProject/ASDKSampleApp/Source/DetailInfo/DetailInfoTableViewController.m#L206-L208

Было бы логичным получать реальные данные из модели и формировать платеж на основе них

**Comment by slavabuv** [comment]
> UPD: Сейчас в приложении платежи захардкожены и никак не связаны с базой данных товаров
> Было бы логичным получать реальные данные из модели и формировать платеж на основе них
про какую реальную базу товаров идет речь?

**Comment by romansavrulin** [comment]
@slavabuv ну там же есть json с описанием товаров для модели. Почему бы оттуда не брать значения динамически, а не просто предоставить пример вызова? На этой же страничке вьюха получает реальные значения оттуда.
