### ISSUE TITLE
Метод ASDK для проведения двухстадийной оплаты 

### ISSUE THREAD

**Issue by artemKolyadin** [TinkoffCreditSystems/tinkoff-asdk-ios#24]
Подскажите пожалуйста как вызвать presentPaymentForm в режиме ХОЛДирования средств, а не моментального списывания. В документации для мобильного SDK нашел только описание web методов, а objective-С методов или их параметров не нашел.. Т.е. метод или конфигурация его параметров, которая холдирует -> возвращает id, по которому в дальнейшем можно вызвать какой-нибудь confirmTransaction или cancelTransaction и передать этот id. 

Заранее благодарен!

**Comment by artemKolyadin** [comment]
UPD: Или это зависит от настроек терминала в личном кабинете?

**Comment by slavabuv** [comment]
Добрый день!
>как вызвать presentPaymentForm в режиме ХОЛДирования средств
указываем при привязке карты cardCheckType, но при оплате решение принимается на стороне сервера
https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/25ed72e9b287fa10b17f7a9ab586a4b3ee182e05/ASDKUI/Payment/PaymentFormStarter/ASDKPaymentFormStarter.h#L195

**Comment by artemKolyadin** [comment]
> Добрый день!
> 
> > как вызвать presentPaymentForm в режиме ХОЛДирования средств
> 
> указываем при привязке карты cardCheckType, но при оплате решение принимается на стороне сервера (привязка карты без оплаты, онлайн документация https://oplata.tinkoff.ru/landing/develop/documentation/Init)
> 
> [tinkoff-asdk-ios/ASDKUI/Payment/PaymentFormStarter/ASDKPaymentFormStarter.h](https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/25ed72e9b287fa10b17f7a9ab586a4b3ee182e05/ASDKUI/Payment/PaymentFormStarter/ASDKPaymentFormStarter.h#L195)
> Line 195 in [25ed72e](/TinkoffCreditSystems/tinkoff-asdk-ios/commit/25ed72e9b287fa10b17f7a9ab586a4b3ee182e05)
>   * @param cardCheckType

Таким образом, если пользователь привязывает карту заранее - можно указать в cardCheckType. 
А если пользователь вводит новую карту при совершении первого платежа, решение принимается согласно настройкам терминала личном кабинете?

**Comment by slavabuv** [comment]
Да.
Для такого случая подойдет https://oplata.tinkoff.ru/landing/develop/test  4. Подтверждение платежа

**Comment by artemKolyadin** [comment]
Премного благодарен!
