### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by goharika** [TinkoffCreditSystems/tinkoff-asdk-ios#27]
Hi
During working with your sample project, which I have turned to swift I have got an issue connected with localization.
It brings only localization keys which is stored in askd UI I guess.
What should I switch or how can I integrate this part.
Please help if someone find such problem.

**Comment by slavabuv** [comment]
Hi!
SDK support RU and EN localizations
try this ASDKLocalized to change or add other localizable strings

**Comment by goharika** [comment]
Yes I know, but I am getting issue or that is not issue just can't find how you are setting the label titles.
I have download the sample project but again the same. 
I am getting this after clicking Pay action. Should your PayController had its default values? It doesn't setting
Such as: acq_saved_card_label
acq_change_card_label
acq_btn_cancel
acq_pay

**Comment by goharika** [comment]
Ok find it, there was forceSetLanguage function, that helps me.
In case somebody needed :)
