### ISSUE TITLE
Ошибка ASDKUI

### ISSUE THREAD

**Issue by denikaev** [TinkoffCreditSystems/tinkoff-asdk-ios#35]
При компиляции приложения выскакивает ошибка, уже переустанавливал подсы и все равно выскакивает эта ошибка.
Command CompileXIB failed with a nonzero exit code.

**Comment by illabo** [comment]
В issue #32 ответ. Разработчики не фиксят давно.

**Comment by denikaev** [comment]
Я связывался с Тиньковым, сказали что фиксят, в течении двух недель обещают пофиксить

**Comment by denikaev** [comment]
Починили
