### ISSUE TITLE
Не передается email в FinishAuthorize при оплате через Apple Pay

### ISSUE THREAD

**Issue by starikovvm** [TinkoffCreditSystems/tinkoff-asdk-ios#38]
При оплате через apple pay, email для завершения авторизации берется из `PKPayment`
https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/873d682ae4419aab7e2ff3e8d767ea8fa1e4e0e4/ASDKUI/Payment/PaymentFormStarter/ASDKPaymentFormStarter.m#L553

Проблема в том, что все поля у billingContact равны nil, независимо от того, задавался ли адрес почты [здесь](https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/873d682ae4419aab7e2ff3e8d767ea8fa1e4e0e4/ASDKUI/Payment/PaymentFormStarter/ASDKPaymentFormStarter.m#L371). В [документации](https://developer.apple.com/documentation/passkit/pkpaymentrequest/1619221-billingcontact) я нашел следующее:

> Note that a PKContact object that represents a billing contact contains information for only the postalAddress property. All other properties in the object are set to nil.

По видимости, адрес почты стоит хранить где-то отдельно от Apple Pay.

**Comment by illabo** [comment]
PKContact сломан, насколько я понял все при необходимости передают email как аргумент метода payWithApplePay у ASDKPaymentFormStarter. У меня тоже любые платежи, где shippingContact не nil фейлились.
