### ISSUE TITLE
Документация по API?

### ISSUE THREAD

**Issue by AnKariOS** [TinkoffCreditSystems/tinkoff-asdk-ios#4]
Нет никакой документации вообще 
Вроде бы серьезный банк - предоставили SDK, а документации по ней отсутствует полностью.
Прилагаемый пример - кривой, над которым надо "пошаманить" прежде ,чем он запустится.

**Comment by d-tarasov** [comment]
В настоящий момент документация представлена в формате [HeaderDoc](https://www.raywenderlich.com/66395/documenting-in-xcode-with-headerdoc-tutorial) и в виде демо приложения. Будем вам благодарны, если вы укажите в чем кривость примера, и что вы подшаманивали чтобы он запускался
