### ISSUE TITLE
Не вызывается onCancelled при смахивании контроллера с UIModalPresentationFormSheet

### ISSUE THREAD

**Issue by starikovvm** [TinkoffCreditSystems/tinkoff-asdk-ios#43]
В iOS 13 появился жест закрытия экрана с UIModalPresentationFormSheet. Он при этом никак не обрабатывается самим сдк. Хотелось бы либо иметь возможность запретить использование этого жеста (заданием `viewController.modalInPresentation = YES`), либо определять его и вызывать блок onCancelled.

**Comment by AlexShik** [comment]
Да, решение данной проблемы сильно бы помогло. Пример рабочего кода:


``
public override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)

    if isBeingDismissed {
        onCancel()
    }
}
``
