### ISSUE TITLE
Error 9999 при завершении авторизации платежа Apple Pay

### ISSUE THREAD

**Issue by konstructor1** [TinkoffCreditSystems/tinkoff-asdk-ios#44]
Подскажите пожалуйста, как можно решить следующую проблему: 

Использую платежный метод payUsingApplePay класса ASDKPaymentFormStarter.
На этапе завершения авторизации платежа от сервера получаю следующую ошибку: 

Response:
Error Domain=ru.tcsbank.asdk Code=9999 "(null)" UserInfo={errorDetails=Ошибка шифрования карточных данных., errorMessage=Неверные параметры., acquringResponse=ASDKAcquiringResponse object with data:
{
    Details = "\U041e\U0448\U0438\U0431\U043a\U0430 \U0448\U0438\U0444\U0440\U043e\U0432\U0430\U043d\U0438\U044f \U043a\U0430\U0440\U0442\U043e\U0447\U043d\U044b\U0445 \U0434\U0430\U043d\U043d\U044b\U0445.";
    ErrorCode = 9999;
    Message = "\U041d\U0435\U0432\U0435\U0440\U043d\U044b\U0435 \U043f\U0430\U0440\U0430\U043c\U0435\U0442\U0440\U044b.";
    Success = 0;
}}

Использую уже свой Merchant Id, тестовый терминал заведенного аккаунта, тестовую карту Apple, добавленную в Wallet, пользователя Sandbox Testing Account.

**Comment by slavabuv** [comment]
обновили параметры запроса оплаты по ApplePay в версии 1.5 исправлено

**Comment by HappyCodingLover** [comment]
What parameters did you update? @slavabuv
