### ISSUE TITLE
Error Domain=ru.tcsbank.asdk Code=4 "(null)" 

### ISSUE THREAD

**Issue by 3dcafe** [TinkoffCreditSystems/tinkoff-asdk-ios#49]
При создание платежа ошибка:

Error Domain=ru.tcsbank.asdk Code=4 "(null)" UserInfo={errorDetails=Изменение статуса недопустимо., errorMessage=Запрашиваемое состояние транзакции является неверным., acquringResponse=ASDKAcquiringResponse object with data:
{
    Details = "Изменение статуса недопустимо.";
    ErrorCode = 4;
    Message = "Запрашиваемое состояние транзакции является неверным.";
    Success = 0;
}}

Можете подсказать что не так делаем ?

**Comment by slavabuv** [comment]
Details = "Изменение статуса недопустимо.";
Нужно вновь инициализировать платеж и далее уже его (новый) оплачивать.
