### ISSUE TITLE
Проблема с подписью запросов. Постоянная ошибка 205

### ISSUE THREAD

**Issue by SpecProg** [TinkoffCreditSystems/tinkoff-asdk-ios#5]
Как нужно прописать публичный ключ, что бы при запросах не выдавало 205 ошибку?

**Comment by d-tarasov** [comment]
Одной строкой как в примере: https://github.com/TinkoffCreditSystems/tinkoff-asdk-ios/blob/master/SampleProject/ASDKSampleApp/Source/ASDKTestKeys.h#L16

**Comment by SpecProg** [comment]
Ключ прописан одной строкой. Нужно ли изменить .pem файл?

**Comment by d-tarasov** [comment]
Напишите на card_acquiring@tinkoff.ru с описанием проблемы и просьбой проверить ваш ключ. В письме укажите ключ и ответ от сервера.
