### ISSUE TITLE
UserInfo={errorDetails=Terminal not found, errorMessage=Parameters are invalid, acquringResponse=ASDKAcquiringResponse object with data:

### ISSUE THREAD

**Issue by Moskwinow** [TinkoffCreditSystems/tinkoff-asdk-ios#51]
Получаю такую ошибку при попытке платежа картой 
Optional(Error Domain=ru.tcsbank.asdk Code=9999 "(null)" UserInfo={errorDetails=Terminal not found, errorMessage=Parameters are invalid, acquringResponse=ASDKAcquiringResponse object with data:
{
    Details = "Terminal not found";
    ErrorCode = 9999;
    Message = "Parameters are invalid";
    Success = 0;
}})

**Comment by slavabuv** [comment]
Обратитесь в техподдержку для настройки плетежного терминала oplata@tinkoff.ru
