### ISSUE TITLE
Планируется деприкация tinkoff-asdk-ios?

### ISSUE THREAD

**Issue by illabo** [TinkoffCreditSystems/tinkoff-asdk-ios#53]
Появление [AcquiringSdk_IOS](https://github.com/TinkoffCreditSystems/AcquiringSdk_IOS) означает скорую деприкацию 
tinkoff-asdk-ios? Будут ли приниматься пулл-реквесты здесь? Фиксы будут производиться?

**Comment by slavabuv** [comment]
Добрый день! Да, планируется, но для текущей версии только фиксы, новый функционал будет в новой версии.
