### ISSUE TITLE
Ошибка в FinishAuthorize для некоторых клиентов

### ISSUE THREAD

**Issue by illabo** [TinkoffCreditSystems/tinkoff-asdk-ios#55]
Мы пока не можем отказаться от данной библиотеки и перейти на новую, так как наше приложение еще поддерживает iOS 9.
Столкнулись с проблемой: клиенту возвращалась ошибка 102 на любую попытку оплаты. Так как такой ошибки не нашли в документации по api — наш «бизнес» связался с поддержкой. Нам ответили, что оплата возвращала ошибку, из-за того, что передается ipv6 compressed.
> Евгений, здравствуйте.
> Получила ответ от техников:
> Ошибка из-за того, что в метод FinishAuthorize клиент передал параметр IP в виде ip=fe80::7c05:c9ff:fede:2806 Передавать требуется без сокращений. Повторите оплату с корректным IP.

Я так понимаю, что хотя эта версия sdk не рекомендуема, багфиксы еще производите? Погните, пожалуйста `getIPAddresses` в `ASDKUtils.m`, чтобы возвращались ipv6 expanded?

**Comment by grishamsc** [comment]
@illabo здравствуйте, фикс этой проблемы уже готов. в ближайшие дни будет релиз

**Comment by illabo** [comment]
@grishamsc Спасибо большое за быстрый ответ!

**Comment by illabo** [comment]
@grishamsc Здравствуйте, надеюсь вы не отказались от плана пофиксить эту библиотеку?

**Comment by grishamsc** [comment]
@illabo Прошу прощения, что пришлось долго ждать. Вышла новая версия 1.5.5 с исправлением.

**Comment by illabo** [comment]
Спасибо!
