### ISSUE TITLE
Nullability specifier 'nullable' conflicts with existing specifier 'nonnull'

### ISSUE THREAD

**Issue by SeRG1k17** [TinkoffCreditSystems/tinkoff-asdk-ios#6]
Xcode 8 error:
![2016-11-16 15 12 19](https://cloud.githubusercontent.com/assets/13317173/20346777/206bd668-ac0f-11e6-9a17-690cc43121fb.png)

**Comment by SeRG1k17** [comment]
fixed, need change to
- (void)webView:(UIWebView *)webView didFailLoadWithError:(**nonnull** NSError *)error

**Comment by slavabuv** [comment]
1 проект, в который встраивается SDK, на swift?
2 для какой версии iOS SDK собираете проект?

**Comment by SeRG1k17** [comment]
1. Проект на ObjC
2. минимальная версия 8.0

А где хоть какая-то документация? Для Android есть, а для iOS пусто

**Comment by SeRG1k17** [comment]
Заменил nullable на nonnull. Перестал ругаться

**Comment by androyell** [comment]
Up. Столкнулся с тем же. На самом деле там достаточно просто убрать модификатор.

**Comment by dx777** [comment]
Сделайте документацию, ироды
