### ISSUE TITLE
Email не передается в контроллер оплаты

### ISSUE THREAD

**Issue by Helvetii951** [TinkoffCreditSystems/tinkoff-asdk-ios#9]
Email, переданный в ASDKPaymentFormStarter нигде не отображается.

`- (void)presentPaymentFormFromViewController:(UIViewController *)presentingViewController
                                     orderId:(NSString *)orderId
                                      amount:(NSNumber *)amount
                                       title:(NSString *)title
                                 description:(NSString *)description
                                      cardId:(NSString *)cardId
                                       email:(NSString *)email
                                 customerKey:(NSString *)customerKey
					   additionalPaymentData:(NSDictionary *)data
                                     success:(void (^)(NSString *paymentId))onSuccess
                                   cancelled:(void (^)())onCancelled
                                       error:(void (^)(ASDKAcquringSdkError *error))onError;`

Не работает передача Email ни через email:(NSString *)email, ни  через additionalPaymentData:(NSDictionary *)data

**Comment by maksimkuznetsov** [comment]
Такая же проблема. @Helvetii951 удалось решить?

**Comment by cashman2100** [comment]
Проблема все еще актуальна
